[theme]
#파란색 ok
#primaryColor="#1c2e3c"
#backgroundColor="#c3d4e3"
#secondaryBackgroundColor="#f6c9eb"
#textColor="#413f23"
primaryColor="#030b03"
backgroundColor="#f5fcf4"
secondaryBackgroundColor="#d2c6b2"
textColor="#452813"
